### ISSUE TITLE
Create and share a WIP repo with a project that uses our SDK with offline support

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1474]
We would like to showcase to the rest of the company where we're currently standing with offline support.

We will achieve this by creating an app that uses our SDK with offline support.

It might be a buggy/alpha state, the most important goal is receiving early feedback and being more transparent.

## Tasks

- [x] Store channels, messages in sqlite database
- [x] Event handling to update the database
- [x] Typescript for database schema to ensure sanity
- [ ] Unit tests
- [x] Usage of sync api to handle connection recovery
- [x] Setup migration strategy
- [x] Upgrade watercooler app to use offline support for testing
